### PR TITLE
Manually Call callOnClick

### PR DESCRIPTION
**Pull request by Glurt**
Added the ability to call callOnClick for an item at a specific
position in the container

### CODE REVIEW

**Comment by shehabic** [comment]
I'm really not sure about this, change? what's the point in it? you already define what happens when an Item is clicked from the beginning via the call-back interface, why would you add this as a public method in the lib? you can simply just trigger this on the interface implementation

**Comment by Glurt** [comment]
You mean manually call the DroppyClickCallbackInterface method? 

How would I know what view and id to pass in?

**Comment by shehabic** [comment]
Here: since this is just a demo example I'm just logging what position of the clicked item. 
https://github.com/shehabic/Droppy/blob/master/samples/src/main/java/com/shehabic/droppy_samples/MainActivity.java#L110

but in a real app I would have something like:
```JAVA
switch (id) {
    case 1:
         callSomeMethod();
         break;
    case 2:
         callAnotherMethod();
         break;
}
```
So if you want to force triggering the last one simply ```callAnotherMethod();```

**Comment by Glurt** [comment]
This is the contents of my call method, like you I'm using a switch statement. 

```java
@Override
    public void call(View view, int id) {
        if (isBusy()) {
            Toast.makeText(this, R.string.camera_busy, Toast.LENGTH_SHORT).show();
        } else {
            switch (id) {
                case R.id.drop_audio:
                    mCaptureType = CaptureTypeEnum.AUDIO;
                    AnimUtils.animateAlpha(mSwitchView, R.drawable.ic_switch_audio);
                    AnimUtils.animateAlpha(mTakeActionView, R.drawable.ic_take_video);
                    hideCamera();
                    break;
                case R.id.drop_picture:
                    mCaptureType = CaptureTypeEnum.IMAGE;
                    AnimUtils.animateAlpha(mSwitchView, R.drawable.ic_switch_camera);
                    AnimUtils.animateAlpha(mTakeActionView, R.drawable.ic_take_photo);
                    showCamera();
                    break;
                case R.id.drop_video:
                    mCaptureType = CaptureTypeEnum.VIDEO;
                    AnimUtils.animateAlpha(mSwitchView, R.drawable.ic_switch_video);
                    AnimUtils.animateAlpha(mTakeActionView, R.drawable.ic_take_video);
                    showCamera();
                    break;
            }
}
```

What you're saying, is that I should take all of the logic out of the switch cases and create individual methods for each case, then call the respective method rather than triggering an onClick event?

What I want is something along the lines of:

````java
final DroppyMenuPopup.Builder dropBuilder = new DroppyMenuPopup.Builder(this, mSwitchView);
        final DroppyMenuPopup build = dropBuilder.fromMenu(R.menu.drop_menu)
                .setOnClick(this)
                .build();

        build.callOnClick(0);
````

If you don't like this idea then maybe have a .setDefaultItem(0) on the Builder.

**Comment by shehabic** [comment]
Default item for what? the popup menu is not supposed to have something selected by default, I'm sorry I don't really get the point, if you wrap this: 
```                    mCaptureType = CaptureTypeEnum.AUDIO;
                    AnimUtils.animateAlpha(mSwitchView, R.drawable.ic_switch_audio);
                    AnimUtils.animateAlpha(mTakeActionView, R.drawable.ic_take_video);
                    hideCamera();
```
into something like:
```captureAudio();```
that would do the job

**Comment by Glurt** [comment]
I'll give you an example use case, one which I'm using here.

I'm using your library to act as a toggle between recording Audio, Video and Images, heres a screenshot: 

image

I want one of these items to be selected by default. It seems logical to me to use the existing functionality that would occur when the menu item is clicked, rather than splitting the code into separate functions just to perform this one task.

Am I using your library wrong?

**Comment by shehabic** [comment]
I'm afraid the popup is stateless, there's no "select" state

**Pull request closed without merging**
