### PR TITLE
Avoid NullPointerException when user clicks repeatedly on a fast way

### PR DESCRIPTION
**Pull request by IvanLopezCarreira**
I've added null checks to avoid NullPointerExceptions in ViewGroup.remove() method

### CODE REVIEW

**Comment by AndresDiazPopov** [comment]
Good solution men.

**Comment by SergioSoftwhisper** [comment]
Nice work man!

**Comment by jchackDragon** [comment]
Good job

**Comment by javieramp** [comment]
**I think this may work!**

**Comment by davidvavra** [comment]
Hi, it looks like this repo is no longer maintained (this PR didn't get merged for 2 months). We created a fork which includes the fix and published it to jcenter: compile 'io.stepuplabs.droppy:droppy:0.6.1.0'

**Pull request merged**
